#! /bin/bash


core=`< "$HMON_DIR/temp1_input"`
echo "   "
echo "323"
if [ "$core" -ge "80000" ];then
  echo "#EE3E38"
elif [ "$core" -ge "70000" ];then
 echo "#F86E51"
elif [ "$core" -ge "60000" ];then
 echo "#FBA465"
elif [ "$core" -ge "50000" ];then
 echo "#F2C85B"
else echo "#e6effc"
fi
